# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Karol Musur
lang: en
description: >-
  I make cool stuff.
logo: /assets/images/cube.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://musur.pl" # the base hostname & protocol for your site, e.g. http://example.com
# Twitter card
twitter:
  username: PanKarol_

# theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-postcss-v2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

postcss:
  cache: false
